# Generated by Django 5.2.7 on 2026-03-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='name',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='description',
            new_name='county_origin',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='created_at',
        ),
    ]
