# Generated by Django 6.0.2 on 2026-02-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
