# Generated by Django 5.2.7 on 2026-03-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
